# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Background.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Background(object):
    def setupUi(self, Background):
        Background.setObjectName("Background")
        Background.resize(1004, 800)
        self.centralwidget = QtWidgets.QWidget(Background)
        self.centralwidget.setObjectName("centralwidget")
        self.btBatdau = QtWidgets.QPushButton(self.centralwidget)
        self.btBatdau.setGeometry(QtCore.QRect(880, 690, 80, 80))
        self.btBatdau.setStyleSheet("border-image: url(:/hinhanh/hinhanh/nutstart.png);")
        self.btBatdau.setText("")
        self.btBatdau.setObjectName("btBatdau")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 0, 701, 251))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 311, 251))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-color: rgb(202, 202, 202);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/hinhanh/hinhanh/idrV1VcT-T_logos.jpeg"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        Background.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Background)
        self.statusbar.setObjectName("statusbar")
        Background.setStatusBar(self.statusbar)

        self.retranslateUi(Background)
        QtCore.QMetaObject.connectSlotsByName(Background)

    def retranslateUi(self, Background):
        _translate = QtCore.QCoreApplication.translate
        Background.setWindowTitle(_translate("Background", "MainWindow"))
        self.label.setText(_translate("Background", "Khóa luận tốt nghiệp"))
import hinhanh_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Background = QtWidgets.QMainWindow()
    ui = Ui_Background()
    ui.setupUi(Background)
    Background.show()
    sys.exit(app.exec_())
