# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(500, 438)
        Login.setStyleSheet("background-color: rgb(65, 153, 163);")
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 80, 381, 281))
        self.groupBox.setStyleSheet("QGroupBox{\n"
"    background-color: rgb(103, 198, 220);\n"
"    border-radius: 20px;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.nhapten = QtWidgets.QLineEdit(self.groupBox)
        self.nhapten.setGeometry(QtCore.QRect(70, 60, 241, 31))
        self.nhapten.setStyleSheet("background-color: rgb(243, 243, 243);\n"
"border-radius: 10px;")
        self.nhapten.setObjectName("nhapten")
        self.matkhau = QtWidgets.QLineEdit(self.groupBox)
        self.matkhau.setGeometry(QtCore.QRect(70, 130, 241, 31))
        self.matkhau.setStyleSheet("background-color: rgb(243, 243, 243);\n"
"border-radius: 10px;")
        self.matkhau.setEchoMode(QtWidgets.QLineEdit.Password)
        self.matkhau.setObjectName("matkhau")
        self.btDangnhap = QtWidgets.QPushButton(self.groupBox)
        self.btDangnhap.setGeometry(QtCore.QRect(70, 200, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.btDangnhap.setFont(font)
        self.btDangnhap.setStyleSheet("border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.btDangnhap.setObjectName("btDangnhap")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(270, 70, 47, 13))
        self.label_2.setStyleSheet("background: transparent; border: none;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/hinhanh/hinhanh/login-form-page-vector-template-your-design-website-ui-concept_986529-484.jpg"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(270, 140, 47, 13))
        self.label_3.setStyleSheet("background: transparent; border: none;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/hinhanh/hinhanh/key.jpg"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 40, 91, 91))
        self.label.setStyleSheet("background: transparent; border: none;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/hinhanh/hinhanh/11zon_cropped.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        Login.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "MainWindow"))
        self.nhapten.setPlaceholderText(_translate("Login", "Tên Đăng Nhập"))
        self.matkhau.setPlaceholderText(_translate("Login", "Mật Khẩu"))
        self.btDangnhap.setText(_translate("Login", "ĐĂNG NHẬP"))
import hinhanh_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
