# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\KL_2025\KLTT\File_QT\Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1932, 1003)
        Main.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_hinhanh = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_hinhanh.setGeometry(QtCore.QRect(10, 10, 1121, 601))
        self.groupBox_hinhanh.setMouseTracking(False)
        self.groupBox_hinhanh.setStyleSheet("QGroupBox {\n"
"    /* Đặt màu viền và độ dày */\n"
"    border: 2px solid #CEC2B1; \n"
"    border-radius: 8px;\n"
"    /* Khoảng cách này cực kỳ quan trọng để tiêu đề không đè lên viền */\n"
"    margin-top: 12px; \n"
"    font-weight: bold;\n"
"    color: #048687; /* Màu chữ tiêu đề theo bảng màu */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center; /* Đặt tiêu đề ở giữa */\n"
"    padding: 0 5px; /* Tạo khoảng trắng hai bên chữ tiêu đề */\n"
"}")
        self.groupBox_hinhanh.setTitle("")
        self.groupBox_hinhanh.setObjectName("groupBox_hinhanh")
        self.Anhdaxuly = QtWidgets.QGraphicsView(self.groupBox_hinhanh)
        self.Anhdaxuly.setGeometry(QtCore.QRect(560, 50, 540, 540))
        self.Anhdaxuly.setStyleSheet("QGraphicsView {\n"
"    border: 3px solid #CEC2B1; /* Viền màu be, dày 3px cho nổi bật */\n"
"    background-color: #FFFFFF; /* Đảm bảo nền luôn trắng sạch */\n"
"    border-radius: 4px;        /* Bo góc nhẹ cho hiện đại */\n"
"}")
        self.Anhdaxuly.setObjectName("Anhdaxuly")
        self.label_2 = QtWidgets.QLabel(self.groupBox_hinhanh)
        self.label_2.setGeometry(QtCore.QRect(560, 10, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(4, 134, 135);\n"
"color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.Anhgoc = QtWidgets.QGraphicsView(self.groupBox_hinhanh)
        self.Anhgoc.setGeometry(QtCore.QRect(10, 50, 540, 540))
        self.Anhgoc.setStyleSheet("QGraphicsView {\n"
"    border: 3px solid #CEC2B1; /* Viền màu be, dày 3px cho nổi bật */\n"
"    background-color: #FFFFFF; /* Đảm bảo nền luôn trắng sạch */\n"
"    border-radius: 4px;        /* Bo góc nhẹ cho hiện đại */\n"
"}")
        self.Anhgoc.setObjectName("Anhgoc")
        self.label = QtWidgets.QLabel(self.groupBox_hinhanh)
        self.label.setGeometry(QtCore.QRect(10, 10, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(4, 134, 135);\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox_ketnoi = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_ketnoi.setGeometry(QtCore.QRect(1400, 10, 511, 501))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_ketnoi.setFont(font)
        self.groupBox_ketnoi.setStyleSheet("QGroupBox {\n"
"    /* Đặt màu viền và độ dày */\n"
"    border: 2px solid #CEC2B1; \n"
"    border-radius: 8px;\n"
"    /* Khoảng cách này cực kỳ quan trọng để tiêu đề không đè lên viền */\n"
"    margin-top: 12px; \n"
"    font-weight: bold;\n"
"    color: #048687; /* Màu chữ tiêu đề theo bảng màu */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 2px 15px;\n"
"    \n"
"    /* Chỉnh màu chữ và nền tiêu đề */\n"
"\n"
"    color: #FFFFFF;           /* Chữ trắng */\n"
"    background-color: #048687; /* Nền xanh đậm (theo bảng màu) */\n"
"    border-radius: 4px;       /* Bo góc nhẹ cho phần nền tiêu đề */\n"
"}\n"
"")
        self.groupBox_ketnoi.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_ketnoi.setObjectName("groupBox_ketnoi")
        self.label_9 = QtWidgets.QLabel(self.groupBox_ketnoi)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_ketnoi)
        self.label_10.setGeometry(QtCore.QRect(10, 250, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.cbKetnoicamera = QtWidgets.QComboBox(self.groupBox_ketnoi)
        self.cbKetnoicamera.setGeometry(QtCore.QRect(130, 250, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.cbKetnoicamera.setFont(font)
        self.cbKetnoicamera.setStyleSheet("")
        self.cbKetnoicamera.setObjectName("cbKetnoicamera")
        self.cbKetnoicamera.addItem("")
        self.cbKetnoicamera.addItem("")
        self.cbKetnoicamera.addItem("")
        self.cbKetnoicamera.addItem("")
        self.Idplc = QtWidgets.QTextEdit(self.groupBox_ketnoi)
        self.Idplc.setGeometry(QtCore.QRect(130, 70, 371, 31))
        self.Idplc.setAcceptDrops(True)
        self.Idplc.setStyleSheet("QTextEdit{\n"
"   border: 2px solid #47A3A7; \n"
"    border-radius: 8px;\n"
"}")
        self.Idplc.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Idplc.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Idplc.setUndoRedoEnabled(True)
        self.Idplc.setAcceptRichText(True)
        self.Idplc.setObjectName("Idplc")
        self.label_11 = QtWidgets.QLabel(self.groupBox_ketnoi)
        self.label_11.setGeometry(QtCore.QRect(50, 70, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_ketnoi)
        self.label_12.setGeometry(QtCore.QRect(50, 130, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.Rackplc = QtWidgets.QTextEdit(self.groupBox_ketnoi)
        self.Rackplc.setGeometry(QtCore.QRect(130, 130, 131, 31))
        self.Rackplc.setStyleSheet("QTextEdit{\n"
"   border: 2px solid #47A3A7; \n"
"    border-radius: 8px;\n"
"}")
        self.Rackplc.setObjectName("Rackplc")
        self.Slotplc = QtWidgets.QTextEdit(self.groupBox_ketnoi)
        self.Slotplc.setGeometry(QtCore.QRect(360, 130, 141, 31))
        self.Slotplc.setStyleSheet("QTextEdit{\n"
"   border: 2px solid #47A3A7; \n"
"    border-radius: 8px;\n"
"}")
        self.Slotplc.setObjectName("Slotplc")
        self.label_13 = QtWidgets.QLabel(self.groupBox_ketnoi)
        self.label_13.setGeometry(QtCore.QRect(300, 130, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_ketnoi)
        self.label_14.setGeometry(QtCore.QRect(30, 310, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.diachicamera = QtWidgets.QTextEdit(self.groupBox_ketnoi)
        self.diachicamera.setGeometry(QtCore.QRect(130, 310, 221, 31))
        self.diachicamera.setStyleSheet("QTextEdit{\n"
"   border: 2px solid #47A3A7; \n"
"    border-radius: 8px;\n"
"}")
        self.diachicamera.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.diachicamera.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.diachicamera.setObjectName("diachicamera")
        self.btKetnoiplc = QtWidgets.QPushButton(self.groupBox_ketnoi)
        self.btKetnoiplc.setGeometry(QtCore.QRect(130, 200, 121, 41))
        self.btKetnoiplc.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btKetnoiplc.setFont(font)
        self.btKetnoiplc.setStyleSheet("color: rgb(39, 174, 96);\n"
"background-color: rgb(242, 242, 242);\n"
"\n"
"\n"
"")
        self.btKetnoiplc.setObjectName("btKetnoiplc")
        self.btKetnoicamera = QtWidgets.QPushButton(self.groupBox_ketnoi)
        self.btKetnoicamera.setGeometry(QtCore.QRect(140, 420, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.btKetnoicamera.setFont(font)
        self.btKetnoicamera.setStyleSheet("color: rgb(39, 174, 96);\n"
"background-color: rgb(242, 242, 242);\n"
"\n"
"\n"
"")
        self.btKetnoicamera.setObjectName("btKetnoicamera")
        self.btNgatketnoicamera = QtWidgets.QPushButton(self.groupBox_ketnoi)
        self.btNgatketnoicamera.setGeometry(QtCore.QRect(310, 420, 131, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btNgatketnoicamera.setFont(font)
        self.btNgatketnoicamera.setStyleSheet("background-color: rgb(242, 242, 242);\n"
"color: rgb(231, 76, 60);\n"
"\n"
"")
        self.btNgatketnoicamera.setObjectName("btNgatketnoicamera")
        self.btNgatketnoiplc = QtWidgets.QPushButton(self.groupBox_ketnoi)
        self.btNgatketnoiplc.setGeometry(QtCore.QRect(300, 200, 131, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btNgatketnoiplc.setFont(font)
        self.btNgatketnoiplc.setStyleSheet("background-color: rgb(242, 242, 242);\n"
"color: rgb(231, 76, 60);\n"
"\n"
"")
        self.btNgatketnoiplc.setObjectName("btNgatketnoiplc")
        self.groupBox_hienthidl = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_hienthidl.setGeometry(QtCore.QRect(1140, 510, 771, 431))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_hienthidl.setFont(font)
        self.groupBox_hienthidl.setStyleSheet("QGroupBox {\n"
"    /* Đặt màu viền và độ dày */\n"
"    border: 2px solid #CEC2B1; \n"
"    border-radius: 8px;\n"
"    /* Khoảng cách này cực kỳ quan trọng để tiêu đề không đè lên viền */\n"
"    margin-top: 12px; \n"
"    font-weight: bold;\n"
"    color: #048687; /* Màu chữ tiêu đề theo bảng màu */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 2px 15px;\n"
"    \n"
"    /* Chỉnh màu chữ và nền tiêu đề */\n"
"    color: #FFFFFF;           /* Chữ trắng */\n"
"    background-color: #048687; /* Nền xanh đậm (theo bảng màu) */\n"
"    border-radius: 4px;       /* Bo góc nhẹ cho phần nền tiêu đề */\n"
"}")
        self.groupBox_hienthidl.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_hienthidl.setObjectName("groupBox_hienthidl")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_hienthidl)
        self.scrollArea.setGeometry(QtCore.QRect(10, 40, 481, 381))
        self.scrollArea.setStyleSheet("/* Chỉnh viền tổng thể cho ScrollArea */\n"
"QScrollArea {\n"
"    border: 2px solid #CEC2B1; /* Màu be trung tính đồng bộ với GroupBox */\n"
"    border-radius: 5px;        /* Bo góc nhẹ cho hiện đại */\n"
"    background-color: #FFFFFF; /* Đảm bảo nền trắng sạch */\n"
"}\n"
"\n"
"/* Quan trọng: Chỉnh viền cho vùng nội dung bên trong để không bị đè viền */\n"
"QScrollArea #scrollAreaWidgetContents {\n"
"    background-color: #FFFFFF;\n"
"}")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 460, 360))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.Hienthidulieu = QtWidgets.QListView(self.scrollAreaWidgetContents_2)
        self.Hienthidulieu.setGeometry(QtCore.QRect(0, 0, 461, 361))
        self.Hienthidulieu.setObjectName("Hienthidulieu")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox_hienthidl)
        self.dateTimeEdit.setGeometry(QtCore.QRect(530, 80, 194, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setStyleSheet("QDateTimeEdit{\n"
"   border: 2px solid #47A3A7; \n"
"    border-radius: 8px;\n"
"}")
        self.dateTimeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.btXuat = QtWidgets.QPushButton(self.groupBox_hienthidl)
        self.btXuat.setGeometry(QtCore.QRect(540, 150, 131, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btXuat.setFont(font)
        self.btXuat.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btXuat.setStyleSheet("color: rgb(39, 174, 96);\n"
"background-color: rgb(242, 242, 242);\n"
"\n"
"\n"
"")
        self.btXuat.setObjectName("btXuat")
        self.groupBox_tuychinhcamera = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_tuychinhcamera.setGeometry(QtCore.QRect(10, 620, 1121, 321))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_tuychinhcamera.setFont(font)
        self.groupBox_tuychinhcamera.setStyleSheet("QGroupBox {\n"
"    /* Đặt màu viền và độ dày */\n"
"    border: 2px solid #CEC2B1; \n"
"    border-radius: 8px;\n"
"    /* Khoảng cách này cực kỳ quan trọng để tiêu đề không đè lên viền */\n"
"    margin-top: 12px; \n"
"    font-weight: bold;\n"
"    color: #048687; /* Màu chữ tiêu đề theo bảng màu */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 2px 15px;\n"
"    \n"
"    /* Chỉnh màu chữ và nền tiêu đề */\n"
"    color: #FFFFFF;           /* Chữ trắng */\n"
"    background-color: #048687; /* Nền xanh đậm (theo bảng màu) */\n"
"    border-radius: 4px;       /* Bo góc nhẹ cho phần nền tiêu đề */\n"
"}")
        self.groupBox_tuychinhcamera.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_tuychinhcamera.setObjectName("groupBox_tuychinhcamera")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_tuychinhcamera)
        self.horizontalSlider.setGeometry(QtCore.QRect(410, 60, 541, 41))
        self.horizontalSlider.setStyleSheet("/* Thanh ray (đường rãnh) */\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #bbb;\n"
"    height: 8px; /* Độ dày thanh ray */\n"
"    background: #E2C0B2;\n"
"    margin: 2px 0;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Nút kéo */\n"
"QSlider::handle:horizontal {\n"
"    background: #008080; /* Màu xanh đồng bộ của bạn */\n"
"    border: 1px solid #005f5f;\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    margin: -7px 0; /* Căn giữa nút kéo so với đường rãnh */\n"
"    border-radius: 9px;\n"
"}\n"
"/* Hiệu ứng khi di chuột qua nút trượt */\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #27ae60;\n"
"}")
        self.horizontalSlider.setMinimum(-50)
        self.horizontalSlider.setMaximum(50)
        self.horizontalSlider.setPageStep(5)
        self.horizontalSlider.setSliderPosition(0)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider.setTickInterval(5)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_16 = QtWidgets.QLabel(self.groupBox_tuychinhcamera)
        self.label_16.setGeometry(QtCore.QRect(40, 60, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.groupBox_tuychinhcamera)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(410, 130, 541, 41))
        self.horizontalSlider_2.setStyleSheet("/* Thanh ray (đường rãnh) */\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #bbb;\n"
"    height: 8px; /* Độ dày thanh ray */\n"
"    background: #E2C0B2;\n"
"    margin: 2px 0;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Nút kéo */\n"
"QSlider::handle:horizontal {\n"
"    background: #008080; /* Màu xanh đồng bộ của bạn */\n"
"    border: 1px solid #005f5f;\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    margin: -7px 0; /* Căn giữa nút kéo so với đường rãnh */\n"
"    border-radius: 9px;\n"
"}\n"
"/* Hiệu ứng khi di chuột qua nút trượt */\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #27ae60;\n"
"}")
        self.horizontalSlider_2.setMinimum(-50)
        self.horizontalSlider_2.setMaximum(50)
        self.horizontalSlider_2.setPageStep(5)
        self.horizontalSlider_2.setSliderPosition(0)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider_2.setTickInterval(5)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.groupBox_tuychinhcamera)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(410, 210, 541, 41))
        self.horizontalSlider_3.setStyleSheet("/* Thanh ray (đường rãnh) */\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #bbb;\n"
"    height: 8px; /* Độ dày thanh ray */\n"
"    background: #E2C0B2;\n"
"    margin: 2px 0;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Nút kéo */\n"
"QSlider::handle:horizontal {\n"
"    background: #008080; /* Màu xanh đồng bộ của bạn */\n"
"    border: 1px solid #005f5f;\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    margin: -7px 0; /* Căn giữa nút kéo so với đường rãnh */\n"
"    border-radius: 9px;\n"
"}\n"
"/* Hiệu ứng khi di chuột qua nút trượt */\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #27ae60;\n"
"}")
        self.horizontalSlider_3.setMinimum(-50)
        self.horizontalSlider_3.setMaximum(50)
        self.horizontalSlider_3.setPageStep(5)
        self.horizontalSlider_3.setSliderPosition(0)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider_3.setTickInterval(5)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.label_17 = QtWidgets.QLabel(self.groupBox_tuychinhcamera)
        self.label_17.setGeometry(QtCore.QRect(40, 130, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_tuychinhcamera)
        self.label_18.setGeometry(QtCore.QRect(40, 210, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.groupBox_hienthikq = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_hienthikq.setGeometry(QtCore.QRect(1140, 10, 251, 501))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_hienthikq.setFont(font)
        self.groupBox_hienthikq.setStyleSheet("QGroupBox {\n"
"    /* Đặt màu viền và độ dày */\n"
"    border: 2px solid #CEC2B1; \n"
"    border-radius: 8px;\n"
"    /* Khoảng cách này cực kỳ quan trọng để tiêu đề không đè lên viền */\n"
"    margin-top: 12px; \n"
"    font-weight: bold;\n"
"    color: #048687; /* Màu chữ tiêu đề theo bảng màu */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 2px 15px;\n"
"    \n"
"    /* Chỉnh màu chữ và nền tiêu đề */\n"
"    color: #FFFFFF;           /* Chữ trắng */\n"
"    background-color: #048687; /* Nền xanh đậm (theo bảng màu) */\n"
"    border-radius: 4px;       /* Bo góc nhẹ cho phần nền tiêu đề */\n"
"}")
        self.groupBox_hienthikq.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_hienthikq.setObjectName("groupBox_hienthikq")
        self.label_3 = QtWidgets.QLabel(self.groupBox_hienthikq)
        self.label_3.setGeometry(QtCore.QRect(70, 200, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(22, 147, 147);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_hienthikq)
        self.label_4.setGeometry(QtCore.QRect(90, 280, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel\n"
"{\n"
"   border: 2px solid #47A3A7; \n"
"    border-radius: 8px;\n"
"\n"
"}")
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_hienthikq)
        self.label_5.setGeometry(QtCore.QRect(20, 430, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel\n"
"{\n"
"   border: 2px solid #47A3A7; \n"
"    border-radius: 8px;\n"
"\n"
"}")
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_hienthikq)
        self.label_6.setGeometry(QtCore.QRect(20, 360, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(52, 157, 0);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_hienthikq)
        self.label_7.setGeometry(QtCore.QRect(160, 430, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel\n"
"{\n"
"   border: 2px solid #47A3A7; \n"
"    border-radius: 8px;\n"
"\n"
"}")
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_hienthikq)
        self.label_8.setGeometry(QtCore.QRect(140, 360, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_15 = QtWidgets.QLabel(self.groupBox_hienthikq)
        self.label_15.setGeometry(QtCore.QRect(40, 40, 181, 161))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel\n"
"{\n"
"   border: 2px solid #47A3A7; \n"
"    border-radius: 8px;\n"
"\n"
"}")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        Main.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "MainWindow"))
        self.label_2.setText(_translate("Main", "ẢNH ĐÃ XỬ LÝ "))
        self.label.setText(_translate("Main", "ẢNH GỐC"))
        self.groupBox_ketnoi.setTitle(_translate("Main", "KẾT NỐI "))
        self.label_9.setText(_translate("Main", "Kết Nối PLC"))
        self.label_10.setText(_translate("Main", "Kết Nối Camera"))
        self.cbKetnoicamera.setItemText(0, _translate("Main", "Camera_custom"))
        self.cbKetnoicamera.setItemText(1, _translate("Main", "Webcam"))
        self.cbKetnoicamera.setItemText(2, _translate("Main", "Camera_GIE"))
        self.cbKetnoicamera.setItemText(3, _translate("Main", "Camera_USB"))
        self.label_11.setText(_translate("Main", "IP_PLC"))
        self.label_12.setText(_translate("Main", "Rack"))
        self.label_13.setText(_translate("Main", "Slot"))
        self.label_14.setText(_translate("Main", "Địa chỉ Camera"))
        self.btKetnoiplc.setText(_translate("Main", "Kết nối PLC"))
        self.btKetnoicamera.setText(_translate("Main", "Kết nối Camera"))
        self.btNgatketnoicamera.setText(_translate("Main", "Ngắt kết nối camera"))
        self.btNgatketnoiplc.setText(_translate("Main", "Ngắt kết nối plc"))
        self.groupBox_hienthidl.setTitle(_translate("Main", "HIỂN THỊ DL"))
        self.btXuat.setText(_translate("Main", "Xuất Excel"))
        self.groupBox_tuychinhcamera.setTitle(_translate("Main", "TÙY CHỈNH CAMERA"))
        self.label_16.setText(_translate("Main", "Độ sáng (Brightness)"))
        self.label_17.setText(_translate("Main", "Độ bão hòa (Saturation)"))
        self.label_18.setText(_translate("Main", "Thời gian phơi sáng (Exposure Time)"))
        self.groupBox_hienthikq.setTitle(_translate("Main", "HIỂN THỊ KQ"))
        self.label_3.setText(_translate("Main", "Tổng số viên "))
        self.label_6.setText(_translate("Main", "Viên đạt "))
        self.label_8.setText(_translate("Main", "Viên lỗi"))
import hinhanh_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
