# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\KL_2025\KLTT\File_QT\Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1932, 1003)
        Main.setStyleSheet("/* Thiết lập cho các GroupBox */\n"
"QGroupBox {\n"
"    border: 2px solid #CEC2B1;\n"
"    border-radius: 8px;\n"
"    margin-top: 15px; /* Tạo khoảng trống cho title */\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center; \n"
"    padding: 2px 20px;\n"
"    background-color: #006666;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border-radius: 5px;\n"
"}\n"
"QMainWindow {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #DCDCDC);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_hinhanh = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_hinhanh.setGeometry(QtCore.QRect(10, 10, 1121, 601))
        self.groupBox_hinhanh.setMouseTracking(False)
        self.groupBox_hinhanh.setStyleSheet("")
        self.groupBox_hinhanh.setTitle("")
        self.groupBox_hinhanh.setObjectName("groupBox_hinhanh")
        self.Anhdaxuly = QtWidgets.QGraphicsView(self.groupBox_hinhanh)
        self.Anhdaxuly.setGeometry(QtCore.QRect(560, 50, 540, 540))
        self.Anhdaxuly.setStyleSheet("QGraphicsView {\n"
"    border: 3px solid #CEC2B1; /* Viền màu be, dày 3px cho nổi bật */\n"
"    background-color: #FFFFFF; /* Đảm bảo nền luôn trắng sạch */\n"
"    border-radius: 4px;        /* Bo góc nhẹ cho hiện đại */\n"
"}")
        self.Anhdaxuly.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Anhdaxuly.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Anhdaxuly.setObjectName("Anhdaxuly")
        self.label_2 = QtWidgets.QLabel(self.groupBox_hinhanh)
        self.label_2.setGeometry(QtCore.QRect(560, 10, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: #006666;\n"
"color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.Anhgoc = QtWidgets.QGraphicsView(self.groupBox_hinhanh)
        self.Anhgoc.setGeometry(QtCore.QRect(10, 50, 540, 540))
        self.Anhgoc.setStyleSheet("QGraphicsView {\n"
"    border: 3px solid #CEC2B1; /* Viền màu be, dày 3px cho nổi bật */\n"
"    background-color: #FFFFFF; /* Đảm bảo nền luôn trắng sạch */\n"
"    border-radius: 4px;        /* Bo góc nhẹ cho hiện đại */\n"
"}")
        self.Anhgoc.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Anhgoc.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Anhgoc.setObjectName("Anhgoc")
        self.label = QtWidgets.QLabel(self.groupBox_hinhanh)
        self.label.setGeometry(QtCore.QRect(10, 10, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: #006666;\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox_ketnoi = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_ketnoi.setGeometry(QtCore.QRect(1400, 10, 511, 531))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_ketnoi.setFont(font)
        self.groupBox_ketnoi.setStyleSheet("")
        self.groupBox_ketnoi.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_ketnoi.setObjectName("groupBox_ketnoi")
        self.label_9 = QtWidgets.QLabel(self.groupBox_ketnoi)
        self.label_9.setGeometry(QtCore.QRect(10, 360, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_ketnoi)
        self.label_10.setGeometry(QtCore.QRect(10, 230, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.cbKetnoicamera = QtWidgets.QComboBox(self.groupBox_ketnoi)
        self.cbKetnoicamera.setGeometry(QtCore.QRect(130, 230, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.cbKetnoicamera.setFont(font)
        self.cbKetnoicamera.setStyleSheet("border: 2px solid #CEC2B1;\n"
"border-radius: 5px;")
        self.cbKetnoicamera.setObjectName("cbKetnoicamera")
        self.cbKetnoicamera.addItem("")
        self.cbKetnoicamera.addItem("")
        self.cbKetnoicamera.addItem("")
        self.Idplc = QtWidgets.QTextEdit(self.groupBox_ketnoi)
        self.Idplc.setGeometry(QtCore.QRect(130, 400, 371, 31))
        self.Idplc.setAcceptDrops(True)
        self.Idplc.setStyleSheet("QTextEdit{\n"
"border: 2px solid #CEC2B1;\n"
"    border-radius: 5px;\n"
"}")
        self.Idplc.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Idplc.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Idplc.setUndoRedoEnabled(True)
        self.Idplc.setAcceptRichText(True)
        self.Idplc.setObjectName("Idplc")
        self.label_11 = QtWidgets.QLabel(self.groupBox_ketnoi)
        self.label_11.setGeometry(QtCore.QRect(50, 400, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_ketnoi)
        self.label_12.setGeometry(QtCore.QRect(50, 440, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.Rackplc = QtWidgets.QTextEdit(self.groupBox_ketnoi)
        self.Rackplc.setGeometry(QtCore.QRect(130, 440, 131, 31))
        self.Rackplc.setStyleSheet("QTextEdit{\n"
" border: 2px solid #CEC2B1;\n"
"border-radius: 5px;\n"
"}")
        self.Rackplc.setObjectName("Rackplc")
        self.Slotplc = QtWidgets.QTextEdit(self.groupBox_ketnoi)
        self.Slotplc.setGeometry(QtCore.QRect(360, 440, 141, 31))
        self.Slotplc.setStyleSheet("QTextEdit{\n"
"border: 2px solid #CEC2B1;\n"
"    border-radius: 5px;\n"
"}")
        self.Slotplc.setObjectName("Slotplc")
        self.label_13 = QtWidgets.QLabel(self.groupBox_ketnoi)
        self.label_13.setGeometry(QtCore.QRect(300, 440, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_ketnoi)
        self.label_14.setGeometry(QtCore.QRect(30, 280, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.diachicamera = QtWidgets.QTextEdit(self.groupBox_ketnoi)
        self.diachicamera.setGeometry(QtCore.QRect(130, 280, 221, 31))
        self.diachicamera.setStyleSheet("QTextEdit{\n"
" border: 2px solid #CEC2B1;\n"
"    border-radius: 5px;\n"
"}")
        self.diachicamera.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.diachicamera.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.diachicamera.setObjectName("diachicamera")
        self.btKetnoiplc = QtWidgets.QPushButton(self.groupBox_ketnoi)
        self.btKetnoiplc.setGeometry(QtCore.QRect(140, 480, 121, 41))
        self.btKetnoiplc.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btKetnoiplc.setFont(font)
        self.btKetnoiplc.setStyleSheet("QPushButton {\n"
"    background-color: #006666;\n"
"    color: white;\n"
"    border: 2px solid #CEC2B1;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #008080; /* Hiệu ứng khi di chuột */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0F6A6A;\n"
"}")
        self.btKetnoiplc.setObjectName("btKetnoiplc")
        self.btKetnoicamera = QtWidgets.QPushButton(self.groupBox_ketnoi)
        self.btKetnoicamera.setGeometry(QtCore.QRect(140, 330, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.btKetnoicamera.setFont(font)
        self.btKetnoicamera.setStyleSheet("QPushButton {\n"
"    background-color: #006666;\n"
"    color: white;\n"
"    border: 2px solid #CEC2B1;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #008080; /* Hiệu ứng khi di chuột */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0F6A6A;\n"
"}")
        self.btKetnoicamera.setObjectName("btKetnoicamera")
        self.btNgatketnoicamera = QtWidgets.QPushButton(self.groupBox_ketnoi)
        self.btNgatketnoicamera.setGeometry(QtCore.QRect(310, 330, 131, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btNgatketnoicamera.setFont(font)
        self.btNgatketnoicamera.setStyleSheet("QPushButton {\n"
"    color: #169393;\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #CEC2B1;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E2C0B2;\n"
"    color: #FFFFFF;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #B5A08C;\n"
"}")
        self.btNgatketnoicamera.setObjectName("btNgatketnoicamera")
        self.btNgatketnoiplc = QtWidgets.QPushButton(self.groupBox_ketnoi)
        self.btNgatketnoiplc.setGeometry(QtCore.QRect(310, 480, 131, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btNgatketnoiplc.setFont(font)
        self.btNgatketnoiplc.setStyleSheet("QPushButton {\n"
"    color: #169393;\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #CEC2B1;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E2C0B2;\n"
"    color: #FFFFFF;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #B5A08C;\n"
"}")
        self.btNgatketnoiplc.setObjectName("btNgatketnoiplc")
        self.cbTaimodel = QtWidgets.QComboBox(self.groupBox_ketnoi)
        self.cbTaimodel.setGeometry(QtCore.QRect(130, 60, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.cbTaimodel.setFont(font)
        self.cbTaimodel.setStyleSheet("border: 2px solid #CEC2B1;\n"
"border-radius: 5px;")
        self.cbTaimodel.setObjectName("cbTaimodel")
        self.cbTaimodel.addItem("")
        self.cbTaimodel.addItem("")
        self.cbTaimodel.addItem("")
        self.btTaimodel = QtWidgets.QPushButton(self.groupBox_ketnoi)
        self.btTaimodel.setGeometry(QtCore.QRect(140, 160, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.btTaimodel.setFont(font)
        self.btTaimodel.setStyleSheet("QPushButton {\n"
"    background-color: #006666;\n"
"    color: white;\n"
"    border: 2px solid #CEC2B1;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #008080; /* Hiệu ứng khi di chuột */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0F6A6A;\n"
"}")
        self.btTaimodel.setObjectName("btTaimodel")
        self.duongdanmodel = QtWidgets.QTextEdit(self.groupBox_ketnoi)
        self.duongdanmodel.setGeometry(QtCore.QRect(130, 110, 221, 31))
        self.duongdanmodel.setStyleSheet("QTextEdit{\n"
"border: 2px solid #CEC2B1;\n"
"    border-radius: 5px;\n"
"}")
        self.duongdanmodel.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.duongdanmodel.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.duongdanmodel.setObjectName("duongdanmodel")
        self.btKhoiphuc = QtWidgets.QPushButton(self.groupBox_ketnoi)
        self.btKhoiphuc.setGeometry(QtCore.QRect(310, 160, 131, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btKhoiphuc.setFont(font)
        self.btKhoiphuc.setStyleSheet("QPushButton {\n"
"    color: #169393;\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #CEC2B1;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E2C0B2;\n"
"    color: #FFFFFF;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #B5A08C;\n"
"}")
        self.btKhoiphuc.setObjectName("btKhoiphuc")
        self.label_15 = QtWidgets.QLabel(self.groupBox_ketnoi)
        self.label_15.setGeometry(QtCore.QRect(10, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.btBrowser = QtWidgets.QPushButton(self.groupBox_ketnoi)
        self.btBrowser.setGeometry(QtCore.QRect(360, 100, 71, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.btBrowser.setFont(font)
        self.btBrowser.setStyleSheet("QPushButton {\n"
"    background-color: #006666;\n"
"    color: white;\n"
"    border: 2px solid #CEC2B1;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #008080; /* Hiệu ứng khi di chuột */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0F6A6A;\n"
"}")
        self.btBrowser.setObjectName("btBrowser")
        self.groupBox_hienthidl = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_hienthidl.setGeometry(QtCore.QRect(1140, 560, 771, 421))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_hienthidl.setFont(font)
        self.groupBox_hienthidl.setStyleSheet("")
        self.groupBox_hienthidl.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_hienthidl.setObjectName("groupBox_hienthidl")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_hienthidl)
        self.scrollArea.setGeometry(QtCore.QRect(10, 40, 481, 361))
        self.scrollArea.setStyleSheet("/* Chỉnh viền tổng thể cho ScrollArea */\n"
"QScrollArea {\n"
"    border: 2px solid #CEC2B1; /* Màu be trung tính đồng bộ với GroupBox */\n"
"    border-radius: 5px;        /* Bo góc nhẹ cho hiện đại */\n"
"    background-color: #FFFFFF; /* Đảm bảo nền trắng sạch */\n"
"}\n"
"\n"
"/* Quan trọng: Chỉnh viền cho vùng nội dung bên trong để không bị đè viền */\n"
"QScrollArea #scrollAreaWidgetContents {\n"
"    background-color: #FFFFFF;\n"
"}")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 460, 340))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.Hienthidulieu = QtWidgets.QListView(self.scrollAreaWidgetContents_2)
        self.Hienthidulieu.setGeometry(QtCore.QRect(0, 0, 461, 341))
        self.Hienthidulieu.setObjectName("Hienthidulieu")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.btXuat = QtWidgets.QPushButton(self.groupBox_hienthidl)
        self.btXuat.setGeometry(QtCore.QRect(540, 150, 131, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btXuat.setFont(font)
        self.btXuat.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btXuat.setStyleSheet("QPushButton {\n"
"    background-color: #006666;\n"
"    color: white;\n"
"    border: 2px solid #CEC2B1;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #008080; /* Hiệu ứng khi di chuột */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0F6A6A;\n"
"}")
        self.btXuat.setObjectName("btXuat")
        self.btTrigger = QtWidgets.QPushButton(self.groupBox_hienthidl)
        self.btTrigger.setGeometry(QtCore.QRect(540, 230, 131, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btTrigger.setFont(font)
        self.btTrigger.setStyleSheet("QPushButton {\n"
"    background-color: #006666;\n"
"    color: white;\n"
"    border: 2px solid #CEC2B1;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #008080; /* Hiệu ứng khi di chuột */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0F6A6A;\n"
"}")
        self.btTrigger.setObjectName("btTrigger")
        self.btContinue = QtWidgets.QPushButton(self.groupBox_hienthidl)
        self.btContinue.setGeometry(QtCore.QRect(540, 310, 131, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btContinue.setFont(font)
        self.btContinue.setStyleSheet("QPushButton {\n"
"    color: #169393;\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #CEC2B1;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E2C0B2;\n"
"    color: #FFFFFF;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #B5A08C;\n"
"}")
        self.btContinue.setObjectName("btContinue")
        self.groupBox_tuychinhcamera = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_tuychinhcamera.setGeometry(QtCore.QRect(10, 620, 1121, 281))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_tuychinhcamera.setFont(font)
        self.groupBox_tuychinhcamera.setStyleSheet("")
        self.groupBox_tuychinhcamera.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_tuychinhcamera.setObjectName("groupBox_tuychinhcamera")
        self.Slider_Dosang = QtWidgets.QSlider(self.groupBox_tuychinhcamera)
        self.Slider_Dosang.setGeometry(QtCore.QRect(410, 60, 541, 41))
        self.Slider_Dosang.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #bbb;\n"
"    height: 8px;\n"
"    background: #e0d5c1;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #006666;\n"
"    border: 1px solid #004444;\n"
"    width: 18px;\n"
"    margin: -7px 0;\n"
"    border-radius: 4px;\n"
"}")
        self.Slider_Dosang.setMinimum(-50)
        self.Slider_Dosang.setMaximum(50)
        self.Slider_Dosang.setPageStep(5)
        self.Slider_Dosang.setProperty("value", 0)
        self.Slider_Dosang.setSliderPosition(0)
        self.Slider_Dosang.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Dosang.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.Slider_Dosang.setTickInterval(5)
        self.Slider_Dosang.setObjectName("Slider_Dosang")
        self.label_16 = QtWidgets.QLabel(self.groupBox_tuychinhcamera)
        self.label_16.setGeometry(QtCore.QRect(40, 60, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: #006666;")
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.Slider_baohoa = QtWidgets.QSlider(self.groupBox_tuychinhcamera)
        self.Slider_baohoa.setGeometry(QtCore.QRect(410, 170, 541, 41))
        self.Slider_baohoa.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #bbb;\n"
"    height: 8px;\n"
"    background: #e0d5c1;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #006666;\n"
"    border: 1px solid #004444;\n"
"    width: 18px;\n"
"    margin: -7px 0;\n"
"    border-radius: 4px;\n"
"}")
        self.Slider_baohoa.setMinimum(-50)
        self.Slider_baohoa.setMaximum(50)
        self.Slider_baohoa.setPageStep(5)
        self.Slider_baohoa.setProperty("value", 0)
        self.Slider_baohoa.setSliderPosition(0)
        self.Slider_baohoa.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_baohoa.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.Slider_baohoa.setTickInterval(5)
        self.Slider_baohoa.setObjectName("Slider_baohoa")
        self.label_17 = QtWidgets.QLabel(self.groupBox_tuychinhcamera)
        self.label_17.setGeometry(QtCore.QRect(40, 170, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: #006666;")
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.Resset_hinhanh = QtWidgets.QPushButton(self.groupBox_tuychinhcamera)
        self.Resset_hinhanh.setGeometry(QtCore.QRect(1000, 170, 91, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Resset_hinhanh.setFont(font)
        self.Resset_hinhanh.setStyleSheet("QPushButton {\n"
"    color: #169393;\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #CEC2B1;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E2C0B2;\n"
"    color: #FFFFFF;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #B5A08C;\n"
"}")
        self.Resset_hinhanh.setObjectName("Resset_hinhanh")
        self.groupBox_hienthikq = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_hienthikq.setGeometry(QtCore.QRect(1140, 10, 251, 531))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_hienthikq.setFont(font)
        self.groupBox_hienthikq.setStyleSheet("")
        self.groupBox_hienthikq.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_hienthikq.setObjectName("groupBox_hienthikq")
        self.label_3 = QtWidgets.QLabel(self.groupBox_hienthikq)
        self.label_3.setGeometry(QtCore.QRect(70, 200, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(22, 147, 147);\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.Tongsovien = QtWidgets.QLabel(self.groupBox_hienthikq)
        self.Tongsovien.setGeometry(QtCore.QRect(90, 280, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Tongsovien.setFont(font)
        self.Tongsovien.setStyleSheet("QLabel\n"
"{\n"
"   border: 2px solid #47A3A7; \n"
"    border-radius: 8px;\n"
"\n"
"}")
        self.Tongsovien.setText("")
        self.Tongsovien.setAlignment(QtCore.Qt.AlignCenter)
        self.Tongsovien.setWordWrap(False)
        self.Tongsovien.setObjectName("Tongsovien")
        self.Viendat = QtWidgets.QLabel(self.groupBox_hienthikq)
        self.Viendat.setGeometry(QtCore.QRect(30, 430, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Viendat.setFont(font)
        self.Viendat.setStyleSheet("QLabel\n"
"{\n"
"   border: 2px solid green; \n"
"    border-radius: 8px;\n"
"\n"
"}")
        self.Viendat.setText("")
        self.Viendat.setAlignment(QtCore.Qt.AlignCenter)
        self.Viendat.setWordWrap(False)
        self.Viendat.setObjectName("Viendat")
        self.label_6 = QtWidgets.QLabel(self.groupBox_hienthikq)
        self.label_6.setGeometry(QtCore.QRect(20, 360, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(52, 157, 0);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.Vienloi = QtWidgets.QLabel(self.groupBox_hienthikq)
        self.Vienloi.setGeometry(QtCore.QRect(160, 430, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Vienloi.setFont(font)
        self.Vienloi.setStyleSheet("QLabel\n"
"{\n"
"   border: 2px solid red; \n"
"    border-radius: 8px;\n"
"\n"
"}")
        self.Vienloi.setText("")
        self.Vienloi.setAlignment(QtCore.Qt.AlignCenter)
        self.Vienloi.setWordWrap(False)
        self.Vienloi.setObjectName("Vienloi")
        self.label_8 = QtWidgets.QLabel(self.groupBox_hienthikq)
        self.label_8.setGeometry(QtCore.QRect(140, 360, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.hienthiKQ = QtWidgets.QLabel(self.groupBox_hienthikq)
        self.hienthiKQ.setGeometry(QtCore.QRect(40, 40, 181, 161))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.hienthiKQ.setFont(font)
        self.hienthiKQ.setStyleSheet("QLabel\n"
"{\n"
"   border: 2px solid #47A3A7; \n"
"    border-radius: 8px;\n"
"\n"
"}")
        self.hienthiKQ.setText("")
        self.hienthiKQ.setObjectName("hienthiKQ")
        Main.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "MainWindow"))
        self.label_2.setText(_translate("Main", "ẢNH ĐÃ XỬ LÝ "))
        self.label.setText(_translate("Main", "ẢNH GỐC"))
        self.groupBox_ketnoi.setTitle(_translate("Main", "KẾT NỐI "))
        self.label_9.setText(_translate("Main", "Kết Nối PLC"))
        self.label_10.setText(_translate("Main", "Kết Nối Camera"))
        self.cbKetnoicamera.setItemText(0, _translate("Main", "Webcam"))
        self.cbKetnoicamera.setItemText(1, _translate("Main", "Camera_USB"))
        self.cbKetnoicamera.setItemText(2, _translate("Main", "Camera_custom"))
        self.label_11.setText(_translate("Main", "IP_PLC"))
        self.label_12.setText(_translate("Main", "Rack"))
        self.label_13.setText(_translate("Main", "Slot"))
        self.label_14.setText(_translate("Main", "Địa chỉ Camera"))
        self.btKetnoiplc.setText(_translate("Main", "Kết nối PLC"))
        self.btKetnoicamera.setText(_translate("Main", "Kết nối Camera"))
        self.btNgatketnoicamera.setText(_translate("Main", "Ngắt kết nối camera"))
        self.btNgatketnoiplc.setText(_translate("Main", "Ngắt kết nối plc"))
        self.cbTaimodel.setItemText(0, _translate("Main", "Default"))
        self.cbTaimodel.setItemText(1, _translate("Main", "OpenVION"))
        self.cbTaimodel.setItemText(2, _translate("Main", "Orther (.pt, .oxxn,....)"))
        self.btTaimodel.setText(_translate("Main", "Tải model"))
        self.btKhoiphuc.setText(_translate("Main", "Khôi phục"))
        self.label_15.setText(_translate("Main", "Tải model"))
        self.btBrowser.setText(_translate("Main", "Browser"))
        self.groupBox_hienthidl.setTitle(_translate("Main", "HIỂN THỊ DL"))
        self.btXuat.setText(_translate("Main", "Xuất Excel"))
        self.btTrigger.setText(_translate("Main", "Trigger"))
        self.btContinue.setText(_translate("Main", "Continue"))
        self.groupBox_tuychinhcamera.setTitle(_translate("Main", "TÙY CHỈNH CAMERA"))
        self.label_16.setText(_translate("Main", "Độ sáng (Brightness)"))
        self.label_17.setText(_translate("Main", "Độ bão hòa (Saturation)"))
        self.Resset_hinhanh.setText(_translate("Main", "RESET"))
        self.groupBox_hienthikq.setTitle(_translate("Main", "HIỂN THỊ KQ"))
        self.label_3.setText(_translate("Main", "Tổng số viên "))
        self.label_6.setText(_translate("Main", "Viên đạt "))
        self.label_8.setText(_translate("Main", "Viên lỗi"))
import hinhanh_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
